
<br>
<br>
<br>
<br>
<br>
<br>
<br>


CONFIG FORM

Configuration PHP <br>

Display errors : <?php echo ini_get("display_errors") ?> <br>
Memory Limit : <?php echo ini_get("memory_limit") ?> <br>
Max Upload File Size : <?php echo ini_get("upload_max_filesize") ?> <br>
Post Max Size : <?php echo ini_get("post_max_size") ?> <br>
Max File Uploads : <?php echo ini_get("max_file_uploads") ?> <br>

Max Execution Time : <?php echo ini_get("max_execution_time") ?> <br>



