<footer id="grid-footer">
    <div id="view-edit-album-container" class="container_12 clearfix">

        <div class="grid_3">

        <form name="form_edit_album" id="form-edit-album">
            <div class="element-container">
                <input type="text" name="name_album" id="name-album" value="" >
            </div>
        </form>

        </div>
        <div class="grid_1">
            <div id="album-privacy" >
                <a href="javascript:;" id="btn-private-album" class="btn">
                    <span class="icon-lock"></span>
                </a>
                <a href="javascript:;" id="btn-public-album" class="btn">
                    <span class="icon-eye-open"></span>
                </a>
            </div>

            <a href="javascript:;" id="btn-delete-album" class="btn">
                <i class="icon-trash"></i>
            </a>



        </div>



        <div id="social" class="grid_2">

            <div id="social-panel">

                <div id="social-form-container" class="twitter">
                    <form name="" id="" enctype="application/x-www-form-urlencoded" method="post" action="#">
                        <textarea name="field_social_form" id="field-social-form" row="300" cols="6" >My Fucking Tweet</textarea>
                        <div class="clearfix"></div>

                        <div id="twitter-container">

                            <div id="twitter-image">

                            </div>

                            <a id="btn-publish-twitter" href="javascript:;" class="btn">
                                <span class="icon-twitter-sign"></span>&nbsp;Tweet this
                            </a>

                        </div>

                        <div id="facebook-container">

                            <div id="facebook-image"></div>

                            <a id="btn-publish-facebook" href="javascript:;" class="btn">
                                <span class="icon-facebook-sign"></span>&nbsp;Share
                            </a>
                        </div>
                    </form>
                </div>
                <div id="social-arrow"></div>
            </div>



            <a href="javascript:;" id="" class="btn">
                <i class="icon-share"></i>
            </a>

            <a href="javascript:;" id="btn-share-twitter" class="btn<?php if (!$this->twitter_enable) { echo " disable";} ?>">
                <i class="icon-twitter-sign"></i>
            </a>

            <a href="javascript:;" id="btn-share-facebook" class="btn<?php if (!$this->facebook_enable) { echo " disable";} ?>">
                <i class="icon-facebook-sign"></i>
            </a>

        </div>
        <div class="grid_6"></div>
    </div>
</footer>